# -*- coding: utf-8 -*-
"""DS 320 Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thSlh1r--X5tdcICij7yJBD_ZAl2ANp_
"""

import pandas as pd

passing = pd.read_csv('/content/2023-2024 Passing NFL.csv')
receiving = pd.read_csv('/content/2023-2024 Receiving NFL.csv')
rushing = pd.read_csv('/content/2023-2024 Rushing NFL.csv')

print(receiving.columns)

newpass = passing.loc[:, ['Rk','Player', 'Tm', 'Age', 'Pos', 'G', 'Cmp%', 'Y/G', 'QBR']]
newpass = newpass[newpass.Rk != 'Rk']
newpass = newpass[newpass.Pos == 'QB']
newpass = newpass.drop(columns = ['Rk'])
newpass

newreceive = receiving.loc[:, ['Rk','Player', 'Tm', 'Age', 'Pos', 'G', 'Ctch%', 'Y/G', 'R/G']]
newreceive = newreceive[newreceive.Rk != 'Rk']
temp = ['WR', 'TE']
newreceive = newreceive[newreceive.Pos.isin(temp) == True]
newreceive = newreceive.drop(columns = ['Rk'])
newreceive

newrush = rushing.loc[:, ['Rk','Player', 'Tm', 'Age', 'Pos', 'Games G', 'Rushing Succ%', 'Rushing Y/A','Rushing Y/G']]
newrush = newrush[newrush.Rk != 'Rk']
newrush = newrush[newrush.Pos == 'RB']
newrush = newrush.drop(columns = ['Rk'])
newrush

newrush.to_csv('RushingData.csv', index=False)
newreceive.to_csv('ReceivingData.csv', index=False)
newpass.to_csv('PassingData.csv', index=False)